{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.21.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.8.3"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.6.0.jar",
          "url": "spring-boot-starter-test-2.6.0.jar",
          "size": 4790,
          "sha512": "5fd57888c984337e3d7c836c1230e038be56f118d838d1db027c05dfa19a7b74fe7de1e812577d920fa85ebbc7c34e8171797f2cf4a21d680704b03745ea3e3d",
          "sha256": "c1dfe63aeec5faf96d72087e12a1a4729f1e3babb89ed1738c16b417d4343091",
          "sha1": "f46420ff59926ec459a5a3439c6b8c0c7ff6a2fe",
          "md5": "d66153ac8e009a4fb9ddf737bf4647f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.21.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.8.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.8.3"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.6.0.jar",
          "url": "spring-boot-starter-test-2.6.0.jar",
          "size": 4790,
          "sha512": "5fd57888c984337e3d7c836c1230e038be56f118d838d1db027c05dfa19a7b74fe7de1e812577d920fa85ebbc7c34e8171797f2cf4a21d680704b03745ea3e3d",
          "sha256": "c1dfe63aeec5faf96d72087e12a1a4729f1e3babb89ed1738c16b417d4343091",
          "sha1": "f46420ff59926ec459a5a3439c6b8c0c7ff6a2fe",
          "md5": "d66153ac8e009a4fb9ddf737bf4647f8"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.6.0.jar",
          "url": "spring-boot-starter-test-2.6.0.jar",
          "size": 4790,
          "sha512": "5fd57888c984337e3d7c836c1230e038be56f118d838d1db027c05dfa19a7b74fe7de1e812577d920fa85ebbc7c34e8171797f2cf4a21d680704b03745ea3e3d",
          "sha256": "c1dfe63aeec5faf96d72087e12a1a4729f1e3babb89ed1738c16b417d4343091",
          "sha1": "f46420ff59926ec459a5a3439c6b8c0c7ff6a2fe",
          "md5": "d66153ac8e009a4fb9ddf737bf4647f8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.6.0.jar",
          "url": "spring-boot-starter-test-2.6.0.jar",
          "size": 4790,
          "sha512": "5fd57888c984337e3d7c836c1230e038be56f118d838d1db027c05dfa19a7b74fe7de1e812577d920fa85ebbc7c34e8171797f2cf4a21d680704b03745ea3e3d",
          "sha256": "c1dfe63aeec5faf96d72087e12a1a4729f1e3babb89ed1738c16b417d4343091",
          "sha1": "f46420ff59926ec459a5a3439c6b8c0c7ff6a2fe",
          "md5": "d66153ac8e009a4fb9ddf737bf4647f8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-test-2.6.0-javadoc.jar",
          "size": 4742,
          "sha512": "2899479924c1ad0ee5342fd3010b6beaf94b63b6974e2d88ec7fd776a82a2953cbea73c7a4bb8b9daa8ee0c38ad5f5143317e31d6ca4cd35a286ecb8b87609fa",
          "sha256": "61089a3062efe679513b05655a479bbb0802bdaff609bd3d6f39e190c8215d36",
          "sha1": "6ffb44da005861a5820d3a65af9a80c821493dc2",
          "md5": "a35d8975ccf2d00135ec69d8f821e9e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.6.0-sources.jar",
          "url": "spring-boot-starter-test-2.6.0-sources.jar",
          "size": 4740,
          "sha512": "7e8ba4c3bbeef5988360082e688eff5e40e3f30e98614ce9eaec74e350740b63e1f6c50dc1f96007e660033404460bf484e3cd6490025b2c6e67c553ca60980c",
          "sha256": "7b6e68adc0628e37640020cde301fa948acd2729a74909be04956c64c32688bf",
          "sha1": "6584e5071fa5ba73456fba6ca742d6677177ef84",
          "md5": "b4774c5f3b4626deff7820ba50e2a064"
        }
      ]
    }
  ]
}
