{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jdbc",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.6.0.jar",
          "url": "spring-boot-starter-jdbc-2.6.0.jar",
          "size": 4768,
          "sha512": "cae7f26dc2afca6ec5d629d6cc1ba6571e1e9737ac078aae97eb4487b18cfd2710bbde4a38841fc2410911f4795c1986c1803b090be4211cb23f410f82a6f610",
          "sha256": "b1795dcdb3b4de9e9fcba17b71749da482e0eb9bb447bd4eba5a4782bbb322a6",
          "sha1": "4281c2237b3fafef40c94cef29623e920b633ab9",
          "md5": "9b0a58097f774908248b494c18a0e1f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.6.0.jar",
          "url": "spring-boot-starter-jdbc-2.6.0.jar",
          "size": 4768,
          "sha512": "cae7f26dc2afca6ec5d629d6cc1ba6571e1e9737ac078aae97eb4487b18cfd2710bbde4a38841fc2410911f4795c1986c1803b090be4211cb23f410f82a6f610",
          "sha256": "b1795dcdb3b4de9e9fcba17b71749da482e0eb9bb447bd4eba5a4782bbb322a6",
          "sha1": "4281c2237b3fafef40c94cef29623e920b633ab9",
          "md5": "9b0a58097f774908248b494c18a0e1f6"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.6.0.jar",
          "url": "spring-boot-starter-jdbc-2.6.0.jar",
          "size": 4768,
          "sha512": "cae7f26dc2afca6ec5d629d6cc1ba6571e1e9737ac078aae97eb4487b18cfd2710bbde4a38841fc2410911f4795c1986c1803b090be4211cb23f410f82a6f610",
          "sha256": "b1795dcdb3b4de9e9fcba17b71749da482e0eb9bb447bd4eba5a4782bbb322a6",
          "sha1": "4281c2237b3fafef40c94cef29623e920b633ab9",
          "md5": "9b0a58097f774908248b494c18a0e1f6"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jdbc-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.6.0.jar",
          "url": "spring-boot-starter-jdbc-2.6.0.jar",
          "size": 4768,
          "sha512": "cae7f26dc2afca6ec5d629d6cc1ba6571e1e9737ac078aae97eb4487b18cfd2710bbde4a38841fc2410911f4795c1986c1803b090be4211cb23f410f82a6f610",
          "sha256": "b1795dcdb3b4de9e9fcba17b71749da482e0eb9bb447bd4eba5a4782bbb322a6",
          "sha1": "4281c2237b3fafef40c94cef29623e920b633ab9",
          "md5": "9b0a58097f774908248b494c18a0e1f6"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jdbc-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-jdbc-2.6.0-javadoc.jar",
          "size": 4743,
          "sha512": "c625d53af04942a56ba9a9a15fe323b447f84be177bf0bff915a513581ab4300bce435fce24aacce3283804c5c7ca6d22ab9f1ee1ffc7a09c8dbe2de3d8be7c5",
          "sha256": "a29af343bdafefef3d23ef9d8b8660f5a518203d86f140adb78f54e8e037c2fc",
          "sha1": "39f61c6b09d7e086281bfb88ec3cb2ce1f50eddd",
          "md5": "615ef5039e36424541c39c0d5c3c45af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-2.6.0-sources.jar",
          "url": "spring-boot-starter-jdbc-2.6.0-sources.jar",
          "size": 4740,
          "sha512": "e8f7113fa6c18112a716e89a7fd393440cdd0c443d7b6013d24454eeafd44d89da3b3917e89fd5eb73ef152e120d68db7fbe5985d9da315f4b724faba2ecb4ff",
          "sha256": "2ab9ea3dfcbf96e1f1f35cf629bc5f0f59b5489a328f66f14addfeed92bc0adc",
          "sha1": "3690d6c8316301048dee69903b5f29bb5dabc2c7",
          "md5": "d286cf284a8a4365f7e7ce2b65b8bd5b"
        }
      ]
    }
  ]
}
