{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "5.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.13.jar",
          "url": "spring-orm-5.3.13.jar",
          "size": 204120,
          "sha512": "cce302343dfdb758c5c07c9a17a6a5c5212388ca8b817ff323f5ddd63e7cf6080e80faa5b43b23f36f2b9fa6c50a777b694013aeeb51ad2e77702e932837ed80",
          "sha256": "d6a7d23e8c5d57000f131abc362c80a1a4afd3bdeaa58cc61108a243273a2bc0",
          "sha1": "cfcd1ea05a881200ddf7c67a1127a0f7c2efcf06",
          "md5": "bef19ce5c8fb4c5dd73c8708ca444d89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.13.jar",
          "url": "spring-orm-5.3.13.jar",
          "size": 204120,
          "sha512": "cce302343dfdb758c5c07c9a17a6a5c5212388ca8b817ff323f5ddd63e7cf6080e80faa5b43b23f36f2b9fa6c50a777b694013aeeb51ad2e77702e932837ed80",
          "sha256": "d6a7d23e8c5d57000f131abc362c80a1a4afd3bdeaa58cc61108a243273a2bc0",
          "sha1": "cfcd1ea05a881200ddf7c67a1127a0f7c2efcf06",
          "md5": "bef19ce5c8fb4c5dd73c8708ca444d89"
        }
      ]
    }
  ]
}
