{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.0.jar",
          "url": "spring-boot-starter-2.6.0.jar",
          "size": 4769,
          "sha512": "9355a1c099ce4c758d2750e115d886223c49e3faf2d2331cda997ef64b1279dc93408bb942bd22446e966ba733ced183778c85d8144a8bc6fdab3fe864116a5b",
          "sha256": "c53ee76b1d31c7f298aed945149d4c27e4e65e76dd3c74e27c879226c60e9e78",
          "sha1": "eaa73f531e85b785b1ba27ff0abf6ced47a79e8d",
          "md5": "a69434f93dadfa82b48373e6d55700a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.0.jar",
          "url": "spring-boot-starter-2.6.0.jar",
          "size": 4769,
          "sha512": "9355a1c099ce4c758d2750e115d886223c49e3faf2d2331cda997ef64b1279dc93408bb942bd22446e966ba733ced183778c85d8144a8bc6fdab3fe864116a5b",
          "sha256": "c53ee76b1d31c7f298aed945149d4c27e4e65e76dd3c74e27c879226c60e9e78",
          "sha1": "eaa73f531e85b785b1ba27ff0abf6ced47a79e8d",
          "md5": "a69434f93dadfa82b48373e6d55700a2"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0.jar",
          "url": "spring-boot-starter-2.6.0.jar",
          "size": 4769,
          "sha512": "9355a1c099ce4c758d2750e115d886223c49e3faf2d2331cda997ef64b1279dc93408bb942bd22446e966ba733ced183778c85d8144a8bc6fdab3fe864116a5b",
          "sha256": "c53ee76b1d31c7f298aed945149d4c27e4e65e76dd3c74e27c879226c60e9e78",
          "sha1": "eaa73f531e85b785b1ba27ff0abf6ced47a79e8d",
          "md5": "a69434f93dadfa82b48373e6d55700a2"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0.jar",
          "url": "spring-boot-starter-2.6.0.jar",
          "size": 4769,
          "sha512": "9355a1c099ce4c758d2750e115d886223c49e3faf2d2331cda997ef64b1279dc93408bb942bd22446e966ba733ced183778c85d8144a8bc6fdab3fe864116a5b",
          "sha256": "c53ee76b1d31c7f298aed945149d4c27e4e65e76dd3c74e27c879226c60e9e78",
          "sha1": "eaa73f531e85b785b1ba27ff0abf6ced47a79e8d",
          "md5": "a69434f93dadfa82b48373e6d55700a2"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-2.6.0-javadoc.jar",
          "size": 4737,
          "sha512": "67636e078c2fdf1ee0062b53e4832187025dc7974ffc98d9ab747fbdd0d611e11d7b300a0b7a6bb8ed82fc46c653572206c15b118cefcf0b4b3bcfa14bb02bee",
          "sha256": "aac2c31e49e925e3d534833e654103fb917d26a856571c1ad67478ce58ce5972",
          "sha1": "20746d777f107c65452b40f26567fd5783722fde",
          "md5": "c50075fe5c4cc404b20ba312678a9180"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-sources.jar",
          "url": "spring-boot-starter-2.6.0-sources.jar",
          "size": 4735,
          "sha512": "c090abd8fa492b36b0a88741ee58fa69e7c933719c8ad40bca66622af5481a70d609d6acfcd3e04810fdaa8a40ba5b3bbc16d1019d2031c95d529e938adb917d",
          "sha256": "bc948c6ec9da32a0d67001d9a06e4166abf977991384f37265af940de6065dc8",
          "sha1": "f72a51757bfdac1ef6561ac2c3e0250a12f5b94d",
          "md5": "75e8212362d890ee6f0c717d8d9adcf4"
        }
      ]
    }
  ]
}
