{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.2.0.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.6.0.jar",
          "url": "spring-boot-starter-validation-2.6.0.jar",
          "size": 4766,
          "sha512": "61470338a45c4d6212adf295d49eeba37126e2b66354da6739f3bc5dc7137a9553c1565dafcbcb3f9f5d6b39321e9cab8952c5a18377cab8fdde2e224e4d7253",
          "sha256": "2e9987ed9de2e783f7d8e9ea6968ed9bd8cadb3e55d35959ee7e178999e0d4bf",
          "sha1": "1d95c8060436fa20bec403daff713d9471a45e58",
          "md5": "ddbf6eb5a9ec763b855e24a4d37df2df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.2.0.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.6.0.jar",
          "url": "spring-boot-starter-validation-2.6.0.jar",
          "size": 4766,
          "sha512": "61470338a45c4d6212adf295d49eeba37126e2b66354da6739f3bc5dc7137a9553c1565dafcbcb3f9f5d6b39321e9cab8952c5a18377cab8fdde2e224e4d7253",
          "sha256": "2e9987ed9de2e783f7d8e9ea6968ed9bd8cadb3e55d35959ee7e178999e0d4bf",
          "sha1": "1d95c8060436fa20bec403daff713d9471a45e58",
          "md5": "ddbf6eb5a9ec763b855e24a4d37df2df"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.6.0.jar",
          "url": "spring-boot-starter-validation-2.6.0.jar",
          "size": 4766,
          "sha512": "61470338a45c4d6212adf295d49eeba37126e2b66354da6739f3bc5dc7137a9553c1565dafcbcb3f9f5d6b39321e9cab8952c5a18377cab8fdde2e224e4d7253",
          "sha256": "2e9987ed9de2e783f7d8e9ea6968ed9bd8cadb3e55d35959ee7e178999e0d4bf",
          "sha1": "1d95c8060436fa20bec403daff713d9471a45e58",
          "md5": "ddbf6eb5a9ec763b855e24a4d37df2df"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.6.0.jar",
          "url": "spring-boot-starter-validation-2.6.0.jar",
          "size": 4766,
          "sha512": "61470338a45c4d6212adf295d49eeba37126e2b66354da6739f3bc5dc7137a9553c1565dafcbcb3f9f5d6b39321e9cab8952c5a18377cab8fdde2e224e4d7253",
          "sha256": "2e9987ed9de2e783f7d8e9ea6968ed9bd8cadb3e55d35959ee7e178999e0d4bf",
          "sha1": "1d95c8060436fa20bec403daff713d9471a45e58",
          "md5": "ddbf6eb5a9ec763b855e24a4d37df2df"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-validation-2.6.0-javadoc.jar",
          "size": 4746,
          "sha512": "3b0f3f615aa603dbbf2e014496124e7e6ccff1d1d46dc71b93b10f862dd631570413aac7da3541ba971c7ebf77c0c1066f80dbf216893fdd4346fd6532487154",
          "sha256": "bf80c8b96ce6646d112833806917bc65164bce9907b7ead69398c92c393d0726",
          "sha1": "8d40ab00345bc352bb50e9ff1b68b3faf10d1baf",
          "md5": "96c57e722daa0f12e45ce9b809ff0b92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.6.0-sources.jar",
          "url": "spring-boot-starter-validation-2.6.0-sources.jar",
          "size": 4744,
          "sha512": "db96ef3999c60ad4a408e3631af2801855d1efba9a0c2c73fcf0115ecf1d1d2e6748ae513347ce3d178bf512445feb08b8c0ddef41415f072ea92fe7f216d569",
          "sha256": "9b710dc6ff88e314e1bead703dca3de839cc88460085d0991396d4811ba32550",
          "sha1": "212bdb580e4a49e83331989f354bc714b3682ad8",
          "md5": "57f21e4221f7abf5747c47d8296a5036"
        }
      ]
    }
  ]
}
