{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-oauth2-jose",
    "version": "5.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-jose-5.6.0.jar",
          "url": "spring-security-oauth2-jose-5.6.0.jar",
          "size": 95229,
          "sha512": "84acbf086b8efcf641df500ddfd4320edc4c0ec0f97e2faf19c5963593f132fa7fff293cdbb8618c0c74d73d0146178b7b2f95345dbc20b367cd3e7206bcccab",
          "sha256": "1120a07bfb54759fe2ebcb430f0f66da35fb67d5c99d79a343eccbea5f1607c2",
          "sha1": "00695349b4a54d397c906c08c15381fb9e4dd24b",
          "md5": "0799b853fb20bb2ac878084ee0046903"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-jose-5.6.0.jar",
          "url": "spring-security-oauth2-jose-5.6.0.jar",
          "size": 95229,
          "sha512": "84acbf086b8efcf641df500ddfd4320edc4c0ec0f97e2faf19c5963593f132fa7fff293cdbb8618c0c74d73d0146178b7b2f95345dbc20b367cd3e7206bcccab",
          "sha256": "1120a07bfb54759fe2ebcb430f0f66da35fb67d5c99d79a343eccbea5f1607c2",
          "sha1": "00695349b4a54d397c906c08c15381fb9e4dd24b",
          "md5": "0799b853fb20bb2ac878084ee0046903"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-jose-5.6.0-javadoc.jar",
          "url": "spring-security-oauth2-jose-5.6.0-javadoc.jar",
          "size": 566433,
          "sha512": "e0c3d188395e96882b73f8664587ca5544493a0128829effb344b06de4c1ba0b6d56a5d6edbae2cdb411b5d03927e7cbb905300ff288ffd87ceece7338073234",
          "sha256": "0409285c69cd401ba6ac6ea1b4423e9e1ef0fe0b133618cecf4eb363ba03e18d",
          "sha1": "9c12e5fbe5fd73ca0fa2c7e34507cc363c3a2464",
          "md5": "ee6a6dbf27484da6cb705821accea921"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-jose-5.6.0-sources.jar",
          "url": "spring-security-oauth2-jose-5.6.0-sources.jar",
          "size": 67110,
          "sha512": "a9fa7fe09df748b0cdde950d731c4627b975deb1f4d060ea575266d421fc52918e3de3960ea9a8fca134e320ff377b489615cefc683e994c58b45987e64f5465",
          "sha256": "d25f7b57d937a78d5cd3a9868969bf08b11cd96b606e3d2f0a003269f0a3e474",
          "sha1": "ef62865d1df6b4d030f62933ff31274cab4128dd",
          "md5": "71cd22d4f0f51b1cd1e80729d573501b"
        }
      ]
    }
  ]
}
