{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.6.0.jar",
          "url": "spring-boot-loader-tools-2.6.0.jar",
          "size": 249410,
          "sha512": "b385e95784046a2cc5c547a77c6deeddfa1a5c8a70db6bce8a1755210f68c1ba69ab67b8eb01279716551113a65a9d3d45d2095dddab0b5084bb354db43aa803",
          "sha256": "3fcd71af82b1eebab6264348c7cc1b230b5f97295a13aac6a7c7d9a1058be6e3",
          "sha1": "19bef9457a032149db016eeb94f7d17208dffda3",
          "md5": "400df675ae64c79e9cdfb2d17de30143"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.6.0.jar",
          "url": "spring-boot-loader-tools-2.6.0.jar",
          "size": 249410,
          "sha512": "b385e95784046a2cc5c547a77c6deeddfa1a5c8a70db6bce8a1755210f68c1ba69ab67b8eb01279716551113a65a9d3d45d2095dddab0b5084bb354db43aa803",
          "sha256": "3fcd71af82b1eebab6264348c7cc1b230b5f97295a13aac6a7c7d9a1058be6e3",
          "sha1": "19bef9457a032149db016eeb94f7d17208dffda3",
          "md5": "400df675ae64c79e9cdfb2d17de30143"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.6.0-javadoc.jar",
          "url": "spring-boot-loader-tools-2.6.0-javadoc.jar",
          "size": 166976,
          "sha512": "3d1b77d1261d126cabf54226ebb25301f11b3515c6ac212aec11143e4674c4faddbcca542cc0c936764d09607e40e36c2c6e98b9e096bc28827f4f9c045e25b7",
          "sha256": "2c38958b16022cc6324744c5a873c0a0f27a269daadc3819a9c96de987b4cf0b",
          "sha1": "8b73316abf839d5321ebe19a2a2236b835030469",
          "md5": "5646a2967082336f2b6fe13e86eb93f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.6.0-sources.jar",
          "url": "spring-boot-loader-tools-2.6.0-sources.jar",
          "size": 69723,
          "sha512": "578ecaa7b2c99c4b3db4422199d58f3b1623e228c0fe9f3fba11be9fea8d2a98328db9bba426e5123f99a2eb42991138335f3eeec4f0789c49eec707b75e3cd2",
          "sha256": "e689459da96503da4eb11e47efd9fcf6bd3177344324fd5de83dde17766eb4e4",
          "sha1": "81824f6fdbed9128896f069ce6740a38d249a29d",
          "md5": "0c4e732e969385fcec212015cda696e4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.6.0.jar",
          "url": "spring-boot-loader-tools-2.6.0.jar",
          "size": 249410,
          "sha512": "b385e95784046a2cc5c547a77c6deeddfa1a5c8a70db6bce8a1755210f68c1ba69ab67b8eb01279716551113a65a9d3d45d2095dddab0b5084bb354db43aa803",
          "sha256": "3fcd71af82b1eebab6264348c7cc1b230b5f97295a13aac6a7c7d9a1058be6e3",
          "sha1": "19bef9457a032149db016eeb94f7d17208dffda3",
          "md5": "400df675ae64c79e9cdfb2d17de30143"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.6.0.jar",
          "url": "spring-boot-loader-tools-2.6.0.jar",
          "size": 249410,
          "sha512": "b385e95784046a2cc5c547a77c6deeddfa1a5c8a70db6bce8a1755210f68c1ba69ab67b8eb01279716551113a65a9d3d45d2095dddab0b5084bb354db43aa803",
          "sha256": "3fcd71af82b1eebab6264348c7cc1b230b5f97295a13aac6a7c7d9a1058be6e3",
          "sha1": "19bef9457a032149db016eeb94f7d17208dffda3",
          "md5": "400df675ae64c79e9cdfb2d17de30143"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "2.6.0"
        }
      ]
    }
  ]
}
