{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0.jar",
          "url": "spring-boot-starter-tomcat-2.6.0.jar",
          "size": 4795,
          "sha512": "6955e4323db0c2380bc863aaa426e97fe06d0eb8146833ba84d366e83e30340c987208e59a25cff67ea9d045fe6d412c9ea28f2977781077e6eb1c6286ef7ba6",
          "sha256": "a7eafc30e697849329663a9f7beada501ab44a82edf24a203512d0f38b654033",
          "sha1": "ec2380a4d60a9dc6cae27e462bb6e52e867547e5",
          "md5": "604c0fde2be1810d2130da63f499b563"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0.jar",
          "url": "spring-boot-starter-tomcat-2.6.0.jar",
          "size": 4795,
          "sha512": "6955e4323db0c2380bc863aaa426e97fe06d0eb8146833ba84d366e83e30340c987208e59a25cff67ea9d045fe6d412c9ea28f2977781077e6eb1c6286ef7ba6",
          "sha256": "a7eafc30e697849329663a9f7beada501ab44a82edf24a203512d0f38b654033",
          "sha1": "ec2380a4d60a9dc6cae27e462bb6e52e867547e5",
          "md5": "604c0fde2be1810d2130da63f499b563"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0.jar",
          "url": "spring-boot-starter-tomcat-2.6.0.jar",
          "size": 4795,
          "sha512": "6955e4323db0c2380bc863aaa426e97fe06d0eb8146833ba84d366e83e30340c987208e59a25cff67ea9d045fe6d412c9ea28f2977781077e6eb1c6286ef7ba6",
          "sha256": "a7eafc30e697849329663a9f7beada501ab44a82edf24a203512d0f38b654033",
          "sha1": "ec2380a4d60a9dc6cae27e462bb6e52e867547e5",
          "md5": "604c0fde2be1810d2130da63f499b563"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0.jar",
          "url": "spring-boot-starter-tomcat-2.6.0.jar",
          "size": 4795,
          "sha512": "6955e4323db0c2380bc863aaa426e97fe06d0eb8146833ba84d366e83e30340c987208e59a25cff67ea9d045fe6d412c9ea28f2977781077e6eb1c6286ef7ba6",
          "sha256": "a7eafc30e697849329663a9f7beada501ab44a82edf24a203512d0f38b654033",
          "sha1": "ec2380a4d60a9dc6cae27e462bb6e52e867547e5",
          "md5": "604c0fde2be1810d2130da63f499b563"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-javadoc.jar",
          "size": 4743,
          "sha512": "14e5ed4aad0ebb77110b6fdba80ea3d2c7ccda2967f3d378c1db67539a12cbfc6a6a9b15fad49854495a714ddf3901af5db6bc1c3ca51bf3b40f6de816c0ab2c",
          "sha256": "5b14015aa5870b0a5d963724e99523d69b3b3f7a89f9d587f63c32480940857c",
          "sha1": "d2902681e1afa9c47255418116657cc40cf3cace",
          "md5": "5fb6b1f25ed4fc627a0da14db6d7acaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-sources.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-sources.jar",
          "size": 4741,
          "sha512": "db717da8983c9985603268533e78a926d7a91423799fc79714dca11393af9c447f70172c547ec2fbdc47d399289682acc9e1013e0da51179ad01dbb0030a9f2b",
          "sha256": "9da8fbb5c5ab213feb187b072996b9c60fd67201a4f33a0e6015031094e8e3b4",
          "sha1": "8f76cc35cbd28999eb3f91d16b8d08695f176601",
          "md5": "89f0590323bc1103a8e487ab552a9eab"
        }
      ]
    }
  ]
}
