{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-devtools",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-2.6.0.jar",
          "url": "spring-boot-devtools-2.6.0.jar",
          "size": 232063,
          "sha512": "5c5c4a8f706674aa85d841e711d36f1623e684829612001db89bf2e29aab9eedcb33c8025ea50ef7b814f235b966ac4a0ef517dc0fb7d23ccccb80e8d7eaca3f",
          "sha256": "ff43b79fd1193e907a245aa09d972d506098bbcaaadc81eb7a968e0ac464e64c",
          "sha1": "aa36b42033b045d6e20b39ef20848e864275b28f",
          "md5": "eda374091ec60188b7db44a5bee0e1b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-2.6.0.jar",
          "url": "spring-boot-devtools-2.6.0.jar",
          "size": 232063,
          "sha512": "5c5c4a8f706674aa85d841e711d36f1623e684829612001db89bf2e29aab9eedcb33c8025ea50ef7b814f235b966ac4a0ef517dc0fb7d23ccccb80e8d7eaca3f",
          "sha256": "ff43b79fd1193e907a245aa09d972d506098bbcaaadc81eb7a968e0ac464e64c",
          "sha1": "aa36b42033b045d6e20b39ef20848e864275b28f",
          "md5": "eda374091ec60188b7db44a5bee0e1b8"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-devtools-2.6.0.jar",
          "url": "spring-boot-devtools-2.6.0.jar",
          "size": 232063,
          "sha512": "5c5c4a8f706674aa85d841e711d36f1623e684829612001db89bf2e29aab9eedcb33c8025ea50ef7b814f235b966ac4a0ef517dc0fb7d23ccccb80e8d7eaca3f",
          "sha256": "ff43b79fd1193e907a245aa09d972d506098bbcaaadc81eb7a968e0ac464e64c",
          "sha1": "aa36b42033b045d6e20b39ef20848e864275b28f",
          "md5": "eda374091ec60188b7db44a5bee0e1b8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-devtools-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-2.6.0.jar",
          "url": "spring-boot-devtools-2.6.0.jar",
          "size": 232063,
          "sha512": "5c5c4a8f706674aa85d841e711d36f1623e684829612001db89bf2e29aab9eedcb33c8025ea50ef7b814f235b966ac4a0ef517dc0fb7d23ccccb80e8d7eaca3f",
          "sha256": "ff43b79fd1193e907a245aa09d972d506098bbcaaadc81eb7a968e0ac464e64c",
          "sha1": "aa36b42033b045d6e20b39ef20848e864275b28f",
          "md5": "eda374091ec60188b7db44a5bee0e1b8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-devtools-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-2.6.0-javadoc.jar",
          "url": "spring-boot-devtools-2.6.0-javadoc.jar",
          "size": 338346,
          "sha512": "202e49cff8088f1070df7f66137644f54112028e343e747f6d0434ad0680c115ea094ff47be48596f072ca808ad3849cb65979695997598439c953fbc7709021",
          "sha256": "6e688eda117e784e7e9f86dbb88802280b8a29afb061001d85348cdbf7bdf61b",
          "sha1": "557f8f23a723a442fcc087e7bc08096dc00478a6",
          "md5": "48a0ecdb559fad36b38e0788671f8578"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-2.6.0-sources.jar",
          "url": "spring-boot-devtools-2.6.0-sources.jar",
          "size": 161008,
          "sha512": "12d22a931c79c8aa3caa3fb46e8bece85d88d7bff372f34e3d75b90a4419c9ee06ef6e203694b035a9a321fe56178364789805e0794e163ba1005df4f7b21318",
          "sha256": "0112b7f1d74d91fdd55280323cc87bc1b3cef032a1aeba6448291aca7f9ba6e5",
          "sha1": "8a95c004f284f242b48f2d3ce91703d9fcfaaa37",
          "md5": "00b77021d767e80f502a3bb12fa639f5"
        }
      ]
    }
  ]
}
