{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "5.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-5.6.0.jar",
          "url": "spring-security-config-5.6.0.jar",
          "size": 1373201,
          "sha512": "808d57e7b88fa5b5fc78e70ae83abfdbab6f4adccfe36f115f1804d40802f4fabc4004f5b98be823531d92b825c338aac7d8399c4c67ac4d616527b5261fdcf5",
          "sha256": "581c238716856330c4536ebb1e78e8fc75091dac75350011b4fcc6fb5b4e6de2",
          "sha1": "9b03cb25f665921db1e6226689ddc7ad53f0f0a3",
          "md5": "260af062a088215adef8b76bf8853bbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-5.6.0.jar",
          "url": "spring-security-config-5.6.0.jar",
          "size": 1373201,
          "sha512": "808d57e7b88fa5b5fc78e70ae83abfdbab6f4adccfe36f115f1804d40802f4fabc4004f5b98be823531d92b825c338aac7d8399c4c67ac4d616527b5261fdcf5",
          "sha256": "581c238716856330c4536ebb1e78e8fc75091dac75350011b4fcc6fb5b4e6de2",
          "sha1": "9b03cb25f665921db1e6226689ddc7ad53f0f0a3",
          "md5": "260af062a088215adef8b76bf8853bbe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-5.6.0-javadoc.jar",
          "url": "spring-security-config-5.6.0-javadoc.jar",
          "size": 1396983,
          "sha512": "7b2245954ab74a35b988cda208e3ee77bac481b5616d24993334a9a3749e6d4dfd44aa7a7f258886c21cdf7132c5dbc82dc6ffee59a030da7f38d382c475d779",
          "sha256": "02aa41f337b962069245bd9c4a20f6e5f3dbd7b3bdbe512b391489721c776663",
          "sha1": "a591232e8043def02ba2bbcf0c5da3ee48c529bc",
          "md5": "3c4636bb0d8c0c800de9bb90ff06c2d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-5.6.0-sources.jar",
          "url": "spring-security-config-5.6.0-sources.jar",
          "size": 945662,
          "sha512": "53d784d2e8ff026d25af18812f3ee0f042e6b9267bf533f6a24527486397aeab0eb2e0cfe6ab0740359b0610c033d7d040497467a6baa2e7ce3a5e173e7af7f5",
          "sha256": "bda90c1163fc00620db20de51b5cd3c97f692260068d1f443da1693a5cc15c4d",
          "sha1": "a4a9553acf39f6f807a10dfd6b43328de52c9589",
          "md5": "d333cd3982cd135798d5631378521080"
        }
      ]
    }
  ]
}
