{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-core",
    "version": "2.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.13.0.jar",
          "url": "jackson-core-2.13.0.jar",
          "size": 374571,
          "sha512": "8a340c9ce19fcf159fc321ff7bf7491b8d60348b472ad4af2bd6e71ef47f1b485afac4d71e734ab6bbf60541a62254ece3f7b12eedd68a88a6623837743d4bd1",
          "sha256": "348bc59b348df2e807b356f1d62d2afb41a974073328abc773eb0932b855d2c8",
          "sha1": "e957ec5442966e69cef543927bdc80e5426968bb",
          "md5": "94e04abccab99e295a3f4f57f6e387c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.13.0.jar",
          "url": "jackson-core-2.13.0.jar",
          "size": 374571,
          "sha512": "8a340c9ce19fcf159fc321ff7bf7491b8d60348b472ad4af2bd6e71ef47f1b485afac4d71e734ab6bbf60541a62254ece3f7b12eedd68a88a6623837743d4bd1",
          "sha256": "348bc59b348df2e807b356f1d62d2afb41a974073328abc773eb0932b855d2c8",
          "sha1": "e957ec5442966e69cef543927bdc80e5426968bb",
          "md5": "94e04abccab99e295a3f4f57f6e387c8"
        }
      ]
    }
  ]
}
