{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.6.0.jar",
          "url": "spring-boot-test-2.6.0.jar",
          "size": 225048,
          "sha512": "714da05253237b55048cbbf704ba049100d07101bac25528a0c3671803a6eef67554ab513651285868d55d44d5328e49e4a2e07986d4654b835f5befc9faedd6",
          "sha256": "46d196a03b60a94701a7c9586946023fef91766f2b553fd4e28bb06f193a0ad2",
          "sha1": "ef36285bd04451cd1d15a6d1349a68045be862f3",
          "md5": "830772204107f01576ca1b63fbae4b4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.6.0.jar",
          "url": "spring-boot-test-2.6.0.jar",
          "size": 225048,
          "sha512": "714da05253237b55048cbbf704ba049100d07101bac25528a0c3671803a6eef67554ab513651285868d55d44d5328e49e4a2e07986d4654b835f5befc9faedd6",
          "sha256": "46d196a03b60a94701a7c9586946023fef91766f2b553fd4e28bb06f193a0ad2",
          "sha1": "ef36285bd04451cd1d15a6d1349a68045be862f3",
          "md5": "830772204107f01576ca1b63fbae4b4e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.6.0-javadoc.jar",
          "url": "spring-boot-test-2.6.0-javadoc.jar",
          "size": 317716,
          "sha512": "31cb9e4009a6c01086f1afd6bbd3d51c9d7da0bbaf8748c2b75636bbdf5ed4812070737ddb5699866624b54e12516b68c31e580245519a68429f3a28c25fc8fb",
          "sha256": "ba202ada4b6a3f146519b03b801df2ee8294c99fe4def1ae07c944dc163c63da",
          "sha1": "56bb3afbab312ab116934fa9a71559a6868c1876",
          "md5": "04ac2d22d348a5c4c7a92d3c52b0886a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.6.0-sources.jar",
          "url": "spring-boot-test-2.6.0-sources.jar",
          "size": 153718,
          "sha512": "d20f89f3e4476833ccaa4294a51f6e5ad2f09bbf3086a343244f96c7d86dd123bc38d6e0ce5e93f2cca11646c4226362eccec07b2780e24c6dbab76823c69087",
          "sha256": "543afe531d20c47e8cf2e7da1cfd662db1b7b2362114c3b23777296b0fc4a7fa",
          "sha1": "6379912adf28c3df846dfa70467543f0ba915c35",
          "md5": "71328c18c3f6e38839f5eb9031edfb71"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-2.6.0.jar",
          "url": "spring-boot-test-2.6.0.jar",
          "size": 225048,
          "sha512": "714da05253237b55048cbbf704ba049100d07101bac25528a0c3671803a6eef67554ab513651285868d55d44d5328e49e4a2e07986d4654b835f5befc9faedd6",
          "sha256": "46d196a03b60a94701a7c9586946023fef91766f2b553fd4e28bb06f193a0ad2",
          "sha1": "ef36285bd04451cd1d15a6d1349a68045be862f3",
          "md5": "830772204107f01576ca1b63fbae4b4e"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.6.0.jar",
          "url": "spring-boot-test-2.6.0.jar",
          "size": 225048,
          "sha512": "714da05253237b55048cbbf704ba049100d07101bac25528a0c3671803a6eef67554ab513651285868d55d44d5328e49e4a2e07986d4654b835f5befc9faedd6",
          "sha256": "46d196a03b60a94701a7c9586946023fef91766f2b553fd4e28bb06f193a0ad2",
          "sha1": "ef36285bd04451cd1d15a6d1349a68045be862f3",
          "md5": "830772204107f01576ca1b63fbae4b4e"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "2.6.0"
        }
      ]
    }
  ]
}
