{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.6.0.jar",
          "url": "spring-boot-test-autoconfigure-2.6.0.jar",
          "size": 189045,
          "sha512": "85ee13fe9ae904870171abf53b3872c97a28e4782649f1a159cc82754a77f9d295709367248d70c571e08a2e4183f55cdf098849a684a11d622839ce38ef9460",
          "sha256": "01b06fb6a44d846e581e2c231866842ca32bf4e548e9c14b2eb013e7ba50827d",
          "sha1": "dc670707f2c5e06344b32083ed80503e2e7f3eb8",
          "md5": "77b967636a716254819d22b092cde40b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.6.0.jar",
          "url": "spring-boot-test-autoconfigure-2.6.0.jar",
          "size": 189045,
          "sha512": "85ee13fe9ae904870171abf53b3872c97a28e4782649f1a159cc82754a77f9d295709367248d70c571e08a2e4183f55cdf098849a684a11d622839ce38ef9460",
          "sha256": "01b06fb6a44d846e581e2c231866842ca32bf4e548e9c14b2eb013e7ba50827d",
          "sha1": "dc670707f2c5e06344b32083ed80503e2e7f3eb8",
          "md5": "77b967636a716254819d22b092cde40b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.6.0-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-2.6.0-javadoc.jar",
          "size": 371901,
          "sha512": "91d33e50ea7f46f8e07aca88f93858898e12fd3e17b427fa03533f5ff397f5bc47ff65b283f3fd3465e679268bff01d963e841bc48d0ce6b9380c1ffee13ad76",
          "sha256": "d46890ec53f7fa016be3764f574095f7ec432e7247e34c81828a353a5fe14196",
          "sha1": "69674a19f00153179d615e0180d5d690e2d3cef1",
          "md5": "d939d1a90c7b3aa25833ff56041c4624"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.6.0-sources.jar",
          "url": "spring-boot-test-autoconfigure-2.6.0-sources.jar",
          "size": 184706,
          "sha512": "1dc410ae189e95a7d89b642269a143bc5e4f4f5e1d31f7336feff09b979e59b4e17a5124195074fbed0f7f5ef34fb5cbb83bde18919c7441ba16281925f78953",
          "sha256": "3e698d42e2ead7830e96cb256604eb44c94b066cc2fe036776d507d1618f4900",
          "sha1": "31103767bdd201c303c3137f9c2615c09194d833",
          "md5": "26af1acbe93fb6cfc4cac69b20dbf4af"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.6.0.jar",
          "url": "spring-boot-test-autoconfigure-2.6.0.jar",
          "size": 189045,
          "sha512": "85ee13fe9ae904870171abf53b3872c97a28e4782649f1a159cc82754a77f9d295709367248d70c571e08a2e4183f55cdf098849a684a11d622839ce38ef9460",
          "sha256": "01b06fb6a44d846e581e2c231866842ca32bf4e548e9c14b2eb013e7ba50827d",
          "sha1": "dc670707f2c5e06344b32083ed80503e2e7f3eb8",
          "md5": "77b967636a716254819d22b092cde40b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.6.0.jar",
          "url": "spring-boot-test-autoconfigure-2.6.0.jar",
          "size": 189045,
          "sha512": "85ee13fe9ae904870171abf53b3872c97a28e4782649f1a159cc82754a77f9d295709367248d70c571e08a2e4183f55cdf098849a684a11d622839ce38ef9460",
          "sha256": "01b06fb6a44d846e581e2c231866842ca32bf4e548e9c14b2eb013e7ba50827d",
          "sha1": "dc670707f2c5e06344b32083ed80503e2e7f3eb8",
          "md5": "77b967636a716254819d22b092cde40b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "2.6.0"
        }
      ]
    }
  ]
}
