{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.13.0.jar",
          "url": "jackson-module-parameter-names-2.13.0.jar",
          "size": 8662,
          "sha512": "883827948d6c050196c682771e41842ec44101703ec742fcdfe3b4c4531b97d71b52a08d121731f403eedab302397591ac2e8abe694fe1776dfa2fe6e443bd7",
          "sha256": "a866e9c939ac518a37b742017ab1a2671d76782f7b8f3943825e677e9dcdae8c",
          "sha1": "9147ae7416d9fdcb2d710161db4414ec400ebdff",
          "md5": "5e89d7faf8d23611dbe002ba9c66ad29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.13.0.jar",
          "url": "jackson-module-parameter-names-2.13.0.jar",
          "size": 8662,
          "sha512": "883827948d6c050196c682771e41842ec44101703ec742fcdfe3b4c4531b97d71b52a08d121731f403eedab302397591ac2e8abe694fe1776dfa2fe6e443bd7",
          "sha256": "a866e9c939ac518a37b742017ab1a2671d76782f7b8f3943825e677e9dcdae8c",
          "sha1": "9147ae7416d9fdcb2d710161db4414ec400ebdff",
          "md5": "5e89d7faf8d23611dbe002ba9c66ad29"
        }
      ]
    }
  ]
}
