{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-2.6.0.jar",
          "url": "spring-boot-starter-json-2.6.0.jar",
          "size": 4745,
          "sha512": "87d77192fdb3b4de9dbed583c21150c14643b3116a423aed2e746591f7055ef8713fb34f02bce6f92dd64e81d143c54b09ed835877e32b1b0d74a53cb40921a8",
          "sha256": "4784918409c543515b419838c34a1135f87fc2afb1f7aeec6ecbb3e5f5f9574c",
          "sha1": "d7b0cf3701abc37d97097bcf9450393c3439fe65",
          "md5": "ddda3b79451b8fa3e4766f5516f65636"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-2.6.0.jar",
          "url": "spring-boot-starter-json-2.6.0.jar",
          "size": 4745,
          "sha512": "87d77192fdb3b4de9dbed583c21150c14643b3116a423aed2e746591f7055ef8713fb34f02bce6f92dd64e81d143c54b09ed835877e32b1b0d74a53cb40921a8",
          "sha256": "4784918409c543515b419838c34a1135f87fc2afb1f7aeec6ecbb3e5f5f9574c",
          "sha1": "d7b0cf3701abc37d97097bcf9450393c3439fe65",
          "md5": "ddda3b79451b8fa3e4766f5516f65636"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.6.0.jar",
          "url": "spring-boot-starter-json-2.6.0.jar",
          "size": 4745,
          "sha512": "87d77192fdb3b4de9dbed583c21150c14643b3116a423aed2e746591f7055ef8713fb34f02bce6f92dd64e81d143c54b09ed835877e32b1b0d74a53cb40921a8",
          "sha256": "4784918409c543515b419838c34a1135f87fc2afb1f7aeec6ecbb3e5f5f9574c",
          "sha1": "d7b0cf3701abc37d97097bcf9450393c3439fe65",
          "md5": "ddda3b79451b8fa3e4766f5516f65636"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.6.0.jar",
          "url": "spring-boot-starter-json-2.6.0.jar",
          "size": 4745,
          "sha512": "87d77192fdb3b4de9dbed583c21150c14643b3116a423aed2e746591f7055ef8713fb34f02bce6f92dd64e81d143c54b09ed835877e32b1b0d74a53cb40921a8",
          "sha256": "4784918409c543515b419838c34a1135f87fc2afb1f7aeec6ecbb3e5f5f9574c",
          "sha1": "d7b0cf3701abc37d97097bcf9450393c3439fe65",
          "md5": "ddda3b79451b8fa3e4766f5516f65636"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-json-2.6.0-javadoc.jar",
          "size": 4743,
          "sha512": "ad2c8b71cb88607b69fa3040f07563f73a0b89b95bb5b8ceac6c53173e2da7126a4997acc064134505237b41e6ab770bb4d00ef4ddbf4649fb535daac9fe5f2a",
          "sha256": "8055839ffa484c97769b03086b51f8a119d115af0455c9f11358bb426c06b66d",
          "sha1": "7b8a127bdafc633f954094041e0ea9790c60d6d2",
          "md5": "c906b621fe1003fa3dc5a743eb083b16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.6.0-sources.jar",
          "url": "spring-boot-starter-json-2.6.0-sources.jar",
          "size": 4740,
          "sha512": "7b483618671b9eb324ea54a1e797ff6c5b3ca3998bf25d138322d03fe7ffcdbe43f325cd313d1d05eae2080dd534225ff4950b8643415d26c648b82256d29f8b",
          "sha256": "820e964606d5b4bd8699ca305e99875d7709c2f1a11cf28b443ee9ef78ba4f37",
          "sha1": "900a99f91804d7445b352327404395c4fb727004",
          "md5": "54a72a4aeb369b0ae6a0732539e9e437"
        }
      ]
    }
  ]
}
