{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-oauth2-core",
    "version": "5.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-5.6.0.jar",
          "url": "spring-security-oauth2-core-5.6.0.jar",
          "size": 94721,
          "sha512": "893980bcfcbedfdb737a8c2f0eeec69ee999816e3556eef1d0aeaad3a3f9015d9d796a11aaa0ebd8bda32f0be6cd12b60eb5b01a588c6d2bb4b414dbea5c8aad",
          "sha256": "4e1f9a72d955100e5bb457cd757e6d2f33c5b96898975bd3be0693a08d6ee243",
          "sha1": "b8d959eac1b3428e77ab61ea90e1824b930cf60b",
          "md5": "0b380a726b82bb24ecaefbe4ea2422b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-oauth2-core-5.6.0.jar",
          "url": "spring-security-oauth2-core-5.6.0.jar",
          "size": 94721,
          "sha512": "893980bcfcbedfdb737a8c2f0eeec69ee999816e3556eef1d0aeaad3a3f9015d9d796a11aaa0ebd8bda32f0be6cd12b60eb5b01a588c6d2bb4b414dbea5c8aad",
          "sha256": "4e1f9a72d955100e5bb457cd757e6d2f33c5b96898975bd3be0693a08d6ee243",
          "sha1": "b8d959eac1b3428e77ab61ea90e1824b930cf60b",
          "md5": "0b380a726b82bb24ecaefbe4ea2422b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-5.6.0-javadoc.jar",
          "url": "spring-security-oauth2-core-5.6.0-javadoc.jar",
          "size": 656688,
          "sha512": "87f8006f9beb3f4e6908788a972c9ff23fbde0462828b5c8274d9b5eed4eab2c19abb9fcd8ce9193493eaebb90700b03ef8c0de3bae1ce0c95c6561233da1693",
          "sha256": "51757159d76bf302248a72110c78559bc5723aacafec3aac412485e2a2310005",
          "sha1": "8a778b161b29044f14f1bf7d70bf4ef8f05bb44c",
          "md5": "e05c1ed84b210bee4a43953f000c3784"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-oauth2-core-5.6.0-sources.jar",
          "url": "spring-security-oauth2-core-5.6.0-sources.jar",
          "size": 91405,
          "sha512": "a4cc7f73bdebe69d3ac5db3be3c9de085430209882d519c376a37ac75978d1ab4164cce72bf9fd4870dd5e4db3aceec869910a363535ed82db3b8a32c35d416e",
          "sha256": "e83ce6d212396f9e933aa74b637a94a7707bbb13c9067547f26f5ea6c4098257",
          "sha1": "2cb58d3612bc2e826d197473d903c573bdb16867",
          "md5": "c56057bbde9ee1a33679d72324af748a"
        }
      ]
    }
  ]
}
