{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.1.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.0.jar",
          "url": "spring-boot-starter-data-jpa-2.6.0.jar",
          "size": 4757,
          "sha512": "d237748e1c0e5bd90e7f9bc8504434fd0e402c6af29e892f55f92c4957aec709918681833417cb2f975397edcb7aad764585f1f3f432f774f82f056e91ed4173",
          "sha256": "578a3b3b30d1adf9919528beb52936e9c276db47441b681c8d4e9747ba96cef7",
          "sha1": "515f5ccf433b375ffdf6ffec27fb08cae3fedaba",
          "md5": "3c25df0363bb6c1f7737574aa5685e11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.1.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.0.jar",
          "url": "spring-boot-starter-data-jpa-2.6.0.jar",
          "size": 4757,
          "sha512": "d237748e1c0e5bd90e7f9bc8504434fd0e402c6af29e892f55f92c4957aec709918681833417cb2f975397edcb7aad764585f1f3f432f774f82f056e91ed4173",
          "sha256": "578a3b3b30d1adf9919528beb52936e9c276db47441b681c8d4e9747ba96cef7",
          "sha1": "515f5ccf433b375ffdf6ffec27fb08cae3fedaba",
          "md5": "3c25df0363bb6c1f7737574aa5685e11"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.0.jar",
          "url": "spring-boot-starter-data-jpa-2.6.0.jar",
          "size": 4757,
          "sha512": "d237748e1c0e5bd90e7f9bc8504434fd0e402c6af29e892f55f92c4957aec709918681833417cb2f975397edcb7aad764585f1f3f432f774f82f056e91ed4173",
          "sha256": "578a3b3b30d1adf9919528beb52936e9c276db47441b681c8d4e9747ba96cef7",
          "sha1": "515f5ccf433b375ffdf6ffec27fb08cae3fedaba",
          "md5": "3c25df0363bb6c1f7737574aa5685e11"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.0.jar",
          "url": "spring-boot-starter-data-jpa-2.6.0.jar",
          "size": 4757,
          "sha512": "d237748e1c0e5bd90e7f9bc8504434fd0e402c6af29e892f55f92c4957aec709918681833417cb2f975397edcb7aad764585f1f3f432f774f82f056e91ed4173",
          "sha256": "578a3b3b30d1adf9919528beb52936e9c276db47441b681c8d4e9747ba96cef7",
          "sha1": "515f5ccf433b375ffdf6ffec27fb08cae3fedaba",
          "md5": "3c25df0363bb6c1f7737574aa5685e11"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.6.0-javadoc.jar",
          "size": 4747,
          "sha512": "a3b3e82ce6d6e9b8cd4a82b587e5f75fe643b63eb575f2b8c5a6c18a6254e97866bee9746671e8ace1470a02a7ad05181f7fcee3f308bf6528d3c5cecba9f513",
          "sha256": "3e6f1524a67b6c01df71727357a3f701161d6df82a2f7fdc31455df5ffbc52a3",
          "sha1": "6a548433577ab4949ecf6fec7e9c1840a64e65ce",
          "md5": "965e9a5315dea8fe6b52f9d7885abd86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.0-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.6.0-sources.jar",
          "size": 4745,
          "sha512": "6fa26a2b7b42feace8b97228a8bad7649c19a7d59aae8e76cc49511d5ccfb12946c395e487193201234c0435778aecf7874c52855b4db47fced3cb6e1dfb801f",
          "sha256": "0cc8cf64c9096310b3d7e615b1a1055ef47755cfea495a6e53d65b83443e82c8",
          "sha1": "b1331dcd6692e0ecbe079851a82c90abc72c0fe7",
          "md5": "e48957d2816dd6858454713b4393cfb3"
        }
      ]
    }
  ]
}
