{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.13.0.jar",
          "url": "jackson-datatype-jsr310-2.13.0.jar",
          "size": 119759,
          "sha512": "409556cc4cbf3948aa515ea63db485b64eaf3705c54574fcc3450ff55f4ccd1bc8b7298363728d9781995fd21bda8daf117f2ee699a4a6f617efed29336ada18",
          "sha256": "b5d3cc4476bff4e5cb41ed485a51852d00d69a85031d2eaa2ce901732af7f1e4",
          "sha1": "1dc28004c274b1ac7b1487ba5831a8b0654abd95",
          "md5": "c0035c4da431eda8520cf888813b87db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.13.0.jar",
          "url": "jackson-datatype-jsr310-2.13.0.jar",
          "size": 119759,
          "sha512": "409556cc4cbf3948aa515ea63db485b64eaf3705c54574fcc3450ff55f4ccd1bc8b7298363728d9781995fd21bda8daf117f2ee699a4a6f617efed29336ada18",
          "sha256": "b5d3cc4476bff4e5cb41ed485a51852d00d69a85031d2eaa2ce901732af7f1e4",
          "sha1": "1dc28004c274b1ac7b1487ba5831a8b0654abd95",
          "md5": "c0035c4da431eda8520cf888813b87db"
        }
      ]
    }
  ]
}
