{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "5.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-5.6.0.jar",
          "url": "spring-security-web-5.6.0.jar",
          "size": 634025,
          "sha512": "53e02bda2f1d58f93ddff14a7f9742912d153faab55e7b04ecb6296992f158a223abb96e59b03b9c41fee88e0275ceef9cb7ae24f273211eea52fd4500dcf38e",
          "sha256": "56ebd99f775a309c70df903211581a303bf89dd7c33e0482049be0e1df2c9a02",
          "sha1": "19c73f6ee2d325b3f007da3ae600f739e28f1bd4",
          "md5": "ab05704c4a1f3af7c1ce604ba176d2e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-5.6.0.jar",
          "url": "spring-security-web-5.6.0.jar",
          "size": 634025,
          "sha512": "53e02bda2f1d58f93ddff14a7f9742912d153faab55e7b04ecb6296992f158a223abb96e59b03b9c41fee88e0275ceef9cb7ae24f273211eea52fd4500dcf38e",
          "sha256": "56ebd99f775a309c70df903211581a303bf89dd7c33e0482049be0e1df2c9a02",
          "sha1": "19c73f6ee2d325b3f007da3ae600f739e28f1bd4",
          "md5": "ab05704c4a1f3af7c1ce604ba176d2e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-5.6.0-javadoc.jar",
          "url": "spring-security-web-5.6.0-javadoc.jar",
          "size": 1934694,
          "sha512": "a04228a17e5f4483e30aa2579342a8dc3fd264b07b0170de8a389a2784653c5e7c8ee2cf8515df19317a7976f372d383ddb44fd6716340eb8315eadcd2034565",
          "sha256": "97c6fa61eb744f71142fce78f86192a9b037e2dbea566ea574c335d887a80c31",
          "sha1": "ee9fcd9b8292655d9b2eca739e95c27b68621903",
          "md5": "a7f29f00e109b3ada32ecd3f644857ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-5.6.0-sources.jar",
          "url": "spring-security-web-5.6.0-sources.jar",
          "size": 568988,
          "sha512": "68f779a6dc98c364c2d926457bb4a24b9eeb6ed3920c97e9e4ba1cec5d10fbeb3ceb08217da72262fc7e36912a6208e4b7064b07ad9a08a3123f7de7a4055884",
          "sha256": "8f69379040aa3ae1f55370ecc19ed1aadff97296d34f819ffed542f3f3dcdd23",
          "sha1": "2bf2535bbcd7b2952e483fcb15f24c3ef2e2e585",
          "md5": "2f27fe87e2f3b512d944087bb8a9dea8"
        }
      ]
    }
  ]
}
