{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jdk8",
    "version": "2.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.13.0.jar",
          "url": "jackson-datatype-jdk8-2.13.0.jar",
          "size": 33813,
          "sha512": "c8bb6b835fbb9d03c9e398edb7187fb0743a9633b5da7fccd305f7579e14ee22e234b3e15c4bcb417a9f96ae0c131cb5e6e1cf044fb47d0ea87996b79a583dd8",
          "sha256": "e6716901676b7f5ede49af2bfcbbe57f5b81475e4bf9d20423cfce8b1fb881ac",
          "sha1": "9635065253dad73ac101351696b58f222d56bdbd",
          "md5": "c91743f50c04f01feec43b6debd965fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.13.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.13.0.jar",
          "url": "jackson-datatype-jdk8-2.13.0.jar",
          "size": 33813,
          "sha512": "c8bb6b835fbb9d03c9e398edb7187fb0743a9633b5da7fccd305f7579e14ee22e234b3e15c4bcb417a9f96ae0c131cb5e6e1cf044fb47d0ea87996b79a583dd8",
          "sha256": "e6716901676b7f5ede49af2bfcbbe57f5b81475e4bf9d20423cfce8b1fb881ac",
          "sha1": "9635065253dad73ac101351696b58f222d56bdbd",
          "md5": "c91743f50c04f01feec43b6debd965fb"
        }
      ]
    }
  ]
}
