{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.6.0.jar",
          "url": "spring-boot-buildpack-platform-2.6.0.jar",
          "size": 241839,
          "sha512": "5fc366415e3c232d6a07d49ff2812a10058306d92a079da0e23c8d65c069bda8980691c61c3f614c5827f678297962207d17116b29b9a985ea6a027e7d00278c",
          "sha256": "e916bb46f1269635bbc2f8be232eeab1e8da949ec67f2f6eae2a832c100449fd",
          "sha1": "690e0de8834ce0d397b927a05b0c363ca9144db0",
          "md5": "7541343b5d99ae1520e3d2c1c0581577"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.6.0.jar",
          "url": "spring-boot-buildpack-platform-2.6.0.jar",
          "size": 241839,
          "sha512": "5fc366415e3c232d6a07d49ff2812a10058306d92a079da0e23c8d65c069bda8980691c61c3f614c5827f678297962207d17116b29b9a985ea6a027e7d00278c",
          "sha256": "e916bb46f1269635bbc2f8be232eeab1e8da949ec67f2f6eae2a832c100449fd",
          "sha1": "690e0de8834ce0d397b927a05b0c363ca9144db0",
          "md5": "7541343b5d99ae1520e3d2c1c0581577"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.6.0-javadoc.jar",
          "url": "spring-boot-buildpack-platform-2.6.0-javadoc.jar",
          "size": 299570,
          "sha512": "513354a60e3e68d887aea48762e9becee823f03182fbcb234abfc6febc7576a97cd997035663224d64b25224a042873ccae603b9dc7de494118725eb0a8e96ca",
          "sha256": "51741a83cbe8e2a6ab4993ed5ea3b9bbfa84785d6e2d1d541118641a08d61768",
          "sha1": "26999f68fd3c33b4044f6f936226f78bdf74c37d",
          "md5": "d52473f31dfecb38ee8f2bde19f7c14c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.6.0-sources.jar",
          "url": "spring-boot-buildpack-platform-2.6.0-sources.jar",
          "size": 157506,
          "sha512": "2a88cae4695bb29b94d0fbb8e2e431a3d2a71a94700431c70dbd1bdd041a329e94e8b7b674c1d3873b1daf45f4bc888f25110d5fd8449ee3c52c9fea32d849de",
          "sha256": "01bb7e32712302a96bb520ddb4a6de0c0564c108c68f71e1cd1872fc1ab3bfde",
          "sha1": "0549168e3a44c7e20f6f564106dc4467b226496d",
          "md5": "837b6234baf45b785da98b595e5ffe1d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.6.0.jar",
          "url": "spring-boot-buildpack-platform-2.6.0.jar",
          "size": 241839,
          "sha512": "5fc366415e3c232d6a07d49ff2812a10058306d92a079da0e23c8d65c069bda8980691c61c3f614c5827f678297962207d17116b29b9a985ea6a027e7d00278c",
          "sha256": "e916bb46f1269635bbc2f8be232eeab1e8da949ec67f2f6eae2a832c100449fd",
          "sha1": "690e0de8834ce0d397b927a05b0c363ca9144db0",
          "md5": "7541343b5d99ae1520e3d2c1c0581577"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.6.0.jar",
          "url": "spring-boot-buildpack-platform-2.6.0.jar",
          "size": 241839,
          "sha512": "5fc366415e3c232d6a07d49ff2812a10058306d92a079da0e23c8d65c069bda8980691c61c3f614c5827f678297962207d17116b29b9a985ea6a027e7d00278c",
          "sha256": "e916bb46f1269635bbc2f8be232eeab1e8da949ec67f2f6eae2a832c100449fd",
          "sha1": "690e0de8834ce0d397b927a05b0c363ca9144db0",
          "md5": "7541343b5d99ae1520e3d2c1c0581577"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.6.0"
        }
      ]
    }
  ]
}
