{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "gvshhhi7mraxrhf4wg5lx2ftka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.6.0.jar",
          "url": "spring-boot-starter-web-2.6.0.jar",
          "size": 4804,
          "sha512": "c3c0865a51fcb2c1cff0f2eb0d32eddce027939e88bb8bba0e69cb88c51d445687ce7ded8d7139ac7f40883eff7605ba3747cf185bb9a9b2d4c252d70264e792",
          "sha256": "13e46e0ec31af9e2488b1e8bc0b190d7a8a1d8f3b2c7ad30e2715672126301b0",
          "sha1": "483a28b67c507a21b8c4ff62d88cd811911e5641",
          "md5": "f001fb6e6a552168c2621dca19906afe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.6.0.jar",
          "url": "spring-boot-starter-web-2.6.0.jar",
          "size": 4804,
          "sha512": "c3c0865a51fcb2c1cff0f2eb0d32eddce027939e88bb8bba0e69cb88c51d445687ce7ded8d7139ac7f40883eff7605ba3747cf185bb9a9b2d4c252d70264e792",
          "sha256": "13e46e0ec31af9e2488b1e8bc0b190d7a8a1d8f3b2c7ad30e2715672126301b0",
          "sha1": "483a28b67c507a21b8c4ff62d88cd811911e5641",
          "md5": "f001fb6e6a552168c2621dca19906afe"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.6.0.jar",
          "url": "spring-boot-starter-web-2.6.0.jar",
          "size": 4804,
          "sha512": "c3c0865a51fcb2c1cff0f2eb0d32eddce027939e88bb8bba0e69cb88c51d445687ce7ded8d7139ac7f40883eff7605ba3747cf185bb9a9b2d4c252d70264e792",
          "sha256": "13e46e0ec31af9e2488b1e8bc0b190d7a8a1d8f3b2c7ad30e2715672126301b0",
          "sha1": "483a28b67c507a21b8c4ff62d88cd811911e5641",
          "md5": "f001fb6e6a552168c2621dca19906afe"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.6.0.jar",
          "url": "spring-boot-starter-web-2.6.0.jar",
          "size": 4804,
          "sha512": "c3c0865a51fcb2c1cff0f2eb0d32eddce027939e88bb8bba0e69cb88c51d445687ce7ded8d7139ac7f40883eff7605ba3747cf185bb9a9b2d4c252d70264e792",
          "sha256": "13e46e0ec31af9e2488b1e8bc0b190d7a8a1d8f3b2c7ad30e2715672126301b0",
          "sha1": "483a28b67c507a21b8c4ff62d88cd811911e5641",
          "md5": "f001fb6e6a552168c2621dca19906afe"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "2.6.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.6.0-javadoc.jar",
          "url": "spring-boot-starter-web-2.6.0-javadoc.jar",
          "size": 4742,
          "sha512": "494b0461325ebaa59de16787988dedc0e5001e3e91e481abec2af4be38cf711d394d219cb98132d2d5bc9f4c7fead1c4382a35cd56855754cdaa2e5fd727027b",
          "sha256": "13acdcad404159753c8bcf5ed1852069bbb29b1de3bce4f79aece0cda02c6c19",
          "sha1": "b3a2c4f5f9788699b6d049db35964f7d02f21d6d",
          "md5": "fabd08dcebd951c1a252e6f24bbf62c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.6.0-sources.jar",
          "url": "spring-boot-starter-web-2.6.0-sources.jar",
          "size": 4740,
          "sha512": "ba54dfb792940a94a6e860d9ab4ea2bbcb0c430a9064e7ab5927113864bb4f69bb2860e9b32e5844c85f00863aad14a00f62408c24236578dfc396457941cb22",
          "sha256": "c4fee77ec02395d7ea6c52c52dde1469319a25443b0eba3b6a83b37b673cb83f",
          "sha1": "daef8974a213bf10691f4c096b92ddb822ee7d9a",
          "md5": "77efc11c7ed88e279c77037807d711da"
        }
      ]
    }
  ]
}
